on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'FastAPI-Azure-Internship'
        publish-profile: '<publishData><publishProfile profileName="FastAPI-Azure-Internship - Web Deploy" publishMethod="MSDeploy" publishUrl="fastapi-azure-internship-eqbgamffauh0cdfq.scm.eastasia-01.azurewebsites.net:443" msdeploySite="FastAPI-Azure-Internship" userName="REDACTED" userPWD="REDACTED" destinationAppUrl="https://fastapi-azure-internship-eqbgamffauh0cdfq.eastasia-01.azurewebsites.net" SQLServerDBConnectionString="REDACTED" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="FastAPI-Azure-Internship - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-hk1-053.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="FastAPI-Azure-Internship\$FastAPI-Azure-Internship" userPWD="btvvff8bgBj40irNxzYzFw0JBJamEDewjF9extjfkLQ4gzo184zByT1Xh6Xb" destinationAppUrl="https://fastapi-azure-internship-eqbgamffauh0cdfq.eastasia-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="FastAPI-Azure-Internship - Zip Deploy" publishMethod="ZipDeploy" publishUrl="fastapi-azure-internship-eqbgamffauh0cdfq.scm.eastasia-01.azurewebsites.net:443" userName="REDACTED" userPWD="REDACTED" destinationAppUrl="https://fastapi-azure-internship-eqbgamffauh0cdfq.eastasia-01.azurewebsites.net" SQLServerDBConnectionString="REDACTED" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
        package: .
